name: Test
on:
  push:
    tags:
      - 'v*.*.*'
#   branches:
#     - update-dependencies

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: hi
        run: |
          echo "${{ github.ref }}"
