name: Test
on:
  push:
    tags:
      - 'rel-*-*-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy-dev
        run: |
          echo "deploying ${{ github.ref }} to dev"
